WIFI_MODE_OFF = "WiFi_OFF"
WIFI_MODE_AP = "WiFi_AP"
WIFI_MODE_CLIENT = "client"
WIFI_MODE_SETUP = "setup_AP"

RELE_BATTERY_LEVEL = "RELE_BATTERY_LEVEL"
RELE_ALWAYS_OFF = "RELE_ALWAYS_OFF"
RELE_ALWAYS_ON = "RELE_ALWAYS_ON"

VIEW_MODE_RELE_SOC_AUTO = "VIEW_MODE_RELE_SOC_AUTO"
VIEW_MODE_WIFI_INFO = "VIEW_MODE_WIFI_INFO"
VIEW_MODE_WIFI_AP_ON = "VIEW_MODE_WIFI_AP_ON"
VIEW_MODE_WIFI_CLI = "VIEW_MODE_WIFI_CLI"
VIEW_MODE_WIFI_OFF = "VIEW_MODE_WIFI_OFF"
VIEW_MODE_SETTING_UP_ON_LEVEL = "VIEW_MODE_SETTING_UP_ON_LEVEL"
VIEW_MODE_SETTING_UP_OFF_LEVEL = "VIEW_MODE_SETTING_UP_OFF_LEVEL"
VIEW_MODE_SETTING_DOWN_ON_LEVEL = "VIEW_MODE_SETTING_DOWN_ON_LEVEL"
VIEW_MODE_SETTING_DOWN_OFF_LEVEL = "VIEW_MODE_SETTING_DOWN_OFF_LEVEL"
VIEW_MODE_RELE_OFF = "VIEW_MODE_RELE_OFF"
VIEW_MODE_RELE_ON = "VIEW_MODE_RELE_ON"
VIEW_MODE_SETTINGS = "VIEW_MODE_SETTINGS"
VIEW_MODE_RESET = "VIEW_MODE_RESET"

EVENT_TYPE_PRESS_BUTTON = "press_button"
EVENT_TYPE_DOUBLE_PRESS_BUTTON = "double_press_button"
EVENT_TYPE_LONG_PRESS_BUTTON = "long_press_button"
EVENT_TYPE_CAN_SOC_READ_WEB = "can_soc_read_web"
EVENT_TYPE_CAN_SOC_READ_OLED = "can_soc_read_oled"
EVENT_TYPE_CAN_SOC_READ_MQTT = "can_soc_read_mqtt"
EVENT_TYPE_CONFIG_UPDATED_MQTT = "config_updated_mqtt"
EVENT_TYPE_CONFIG_UPDATED_WEB = "config_updated_web"
EVENT_TYPE_RELE_ON_OFF_MQTT = "rele_on_off_mqtt"
EVENT_TYPE_MQTT_IN_COMMAND = "mqtt_in_command"
EVENT_TYPE_MQTT_LOG = "event_type_mqtt_log"

TOPIC_COMMAND_RELE_MODE = "rele_mode"
TOPIC_COMMAND_VIEW_MODE = "view_mode"
TOPIC_COMMAND_WIFI_MODE = "wifi_mode"
TOPIC_COMMAND_LEVEL_UP = "level_up"
TOPIC_COMMAND_LEVEL_DOWN = "level_down"
TOPIC_COMMAND_DRAW_LEVEL = "draw_level"







