APP_NAME = "BatteryMonitor"
APP_DOMAIN = "power-storage.eu"

AUTO_CONNECT_TO_WIFI_AP = True
AUTO_SETUP_TIME = True
AUTO_START_WIFI_AP = False
AUTO_START_CAN = True
AUTO_START_WEBREPL = False
AUTO_START_WEBAPP = False
AUTO_START_SETUP_WIFI = False
AUTO_START_UMQTT = True
AUTO_START_OLED = True
AUTO_RESTART_AFTER_UPDATE = False
AUTO_RESTART_IF_NO_WIFI = False

SCREEN_TIMER_SEC = 7
